-- Baseline schema snapshot for mobilnahiska.si, generated by introspecting the
-- live Supabase project (ref uwqnbsjatixrmiugxtkn) on 2026-09-27.
--
-- This is NOT a chronological migration history — no migration files were ever
-- committed to this repo before today, so the exact original DDL for the
-- earliest tables (profiles, plans, etc.) could not be reconstructed honestly.
-- Instead, this file is a complete, verified snapshot of the actual live schema
-- as it exists right now. Run it once against a fresh Supabase project to
-- reproduce the current structure. See supabase/migrations/README.md.
--
-- All schema changes from this point forward should be added as new,
-- sequentially numbered files in this folder (001_..., 002_...), never by
-- editing this file.

-- ============================================================
-- ENUM TYPES
-- ============================================================
create type public.article_status as enum ('draft', 'published');
create type public.comment_status as enum ('pending', 'approved', 'hidden');
create type public.favorite_kind as enum ('listing', 'land');
create type public.inquiry_status as enum ('new', 'contacted', 'closed');
create type public.listing_submission_status as enum ('pending_review', 'published', 'rejected', 'deactivated');
create type public.listing_submission_type as enum ('mobilna', 'modularna', 'zemljisce');
create type public.payment_product_type as enum ('listing', 'plan', 'top_addon', 'homepage_addon');
create type public.payment_status as enum ('pending', 'paid', 'failed', 'cancelled', 'refunded');
create type public.user_role as enum ('user', 'dealer', 'admin');

-- ============================================================
-- FUNCTIONS
-- ============================================================
CREATE OR REPLACE FUNCTION public.prevent_role_self_escalation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.role <> old.role and auth.role() <> 'service_role' then
    new.role := old.role;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.force_comment_pending()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.status := 'pending';
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user_subscription()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.subscriptions (user_id, plan_id, status)
  values (new.id, 'free', 'active');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

-- ============================================================
-- TABLES
-- ============================================================
create table public.admin_audit_log (
  id uuid default gen_random_uuid() not null,
  admin_id uuid not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  before jsonb,
  after jsonb,
  created_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.articles (
  id uuid default gen_random_uuid() not null,
  slug text not null,
  title text not null,
  cover_image_url text,
  excerpt text not null,
  content text[] default '{}'::text[] not null,
  category text not null,
  author text default 'mobilnahiska.si'::text not null,
  seo_title text,
  seo_description text,
  status article_status default 'draft'::article_status not null,
  comments_enabled boolean default true not null,
  published_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.comments (
  id uuid default gen_random_uuid() not null,
  article_slug text not null,
  user_id uuid not null,
  content text not null,
  status comment_status default 'pending'::comment_status not null,
  created_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.email_log (
  id uuid default gen_random_uuid() not null,
  email_type text not null,
  recipient_email text not null,
  dedup_key text not null,
  user_id uuid,
  related_entity_type text,
  related_entity_id text,
  status text not null,
  created_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.favorites (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  kind favorite_kind not null,
  item_slug text not null,
  created_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.inquiries (
  id uuid default gen_random_uuid() not null,
  listing_slug text not null,
  listing_title text not null,
  listing_url text not null,
  seller_name text not null,
  user_id uuid,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  status inquiry_status default 'new'::inquiry_status not null,
  created_at timestamp with time zone default now() not null,
  listing_submission_id uuid,
  PRIMARY KEY (id)
);

create table public.listing_submissions (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  type listing_submission_type not null,
  title text not null,
  description text not null,
  price numeric not null,
  location text not null,
  country text default 'Slovenija'::text not null,
  contact_name text not null,
  contact_phone text not null,
  contact_email text not null,
  condition text,
  manufacturer text,
  year integer,
  area numeric,
  length numeric,
  width numeric,
  bedrooms integer,
  bathrooms integer,
  capacity integer,
  delivery_available boolean,
  land_type text,
  utilities_available boolean,
  photo_urls text[] default '{}'::text[] not null,
  status listing_submission_status default 'pending_review'::listing_submission_status not null,
  created_at timestamp with time zone default now() not null,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  rejection_reason text,
  expires_at timestamp with time zone,
  expiry_reminder_sent_at timestamp with time zone,
  is_top boolean default false not null,
  top_until timestamp with time zone,
  is_featured_homepage boolean default false not null,
  featured_until timestamp with time zone,
  slug text,
  is_exclusive boolean default false not null,
  features text[] default '{}'::text[] not null,
  PRIMARY KEY (id)
);

create table public.payment_provider_events (
  id text not null,
  provider text default 'stripe'::text not null,
  event_type text not null,
  payment_id uuid,
  received_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.payments (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  product_type payment_product_type not null,
  product_id text not null,
  related_entity_type text,
  related_entity_id text,
  amount_cents integer not null,
  currency text default 'eur'::text not null,
  status payment_status default 'pending'::payment_status not null,
  provider text default 'stripe'::text not null,
  provider_session_id text,
  provider_transaction_id text,
  invoice_url text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.plans (
  id text not null,
  name text not null,
  price_cents integer not null,
  billing_period text default 'monthly'::text not null,
  max_active_listings integer,
  description text,
  is_active boolean default true not null,
  features text[] default '{}'::text[] not null,
  is_featured boolean default false not null,
  cta_label text,
  duration_days integer,
  plan_group text,
  stripe_product_id text,
  stripe_price_id text,
  PRIMARY KEY (id)
);

create table public.portal_settings (
  key text not null,
  value text,
  updated_at timestamp with time zone default now() not null,
  PRIMARY KEY (key)
);

create table public.profiles (
  id uuid not null,
  full_name text,
  phone text,
  company_name text,
  role user_role default 'user'::user_role not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  provider_slug text,
  logo_url text,
  description text,
  website text,
  location text,
  PRIMARY KEY (id)
);

create table public.promotion_addons (
  id text not null,
  name text not null,
  price_cents integer not null,
  duration_days integer not null,
  description text,
  cta_label text,
  is_active boolean default true not null,
  updated_at timestamp with time zone default now() not null,
  stripe_product_id text,
  stripe_price_id text,
  PRIMARY KEY (id)
);

create table public.rate_limit_hits (
  id bigint not null,
  bucket_key text not null,
  created_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

create table public.subscriptions (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  plan_id text not null,
  status text default 'active'::text not null,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  billing_interval text,
  started_at timestamp with time zone default now() not null,
  current_period_start timestamp with time zone,
  cancel_at_period_end boolean default false not null,
  provider text default 'stripe'::text not null,
  provider_subscription_id text,
  updated_at timestamp with time zone default now() not null,
  PRIMARY KEY (id)
);

-- ============================================================
-- CONSTRAINTS (unique, foreign key, check — beyond primary keys above)
-- ============================================================
alter table public.admin_audit_log add constraint admin_audit_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.articles add constraint articles_slug_key UNIQUE (slug);
alter table public.comments add constraint comments_content_check CHECK (((char_length(content) >= 1) AND (char_length(content) <= 2000)));
alter table public.comments add constraint comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.comments add constraint comments_article_slug_fkey FOREIGN KEY (article_slug) REFERENCES articles(slug) ON DELETE CASCADE;
alter table public.email_log add constraint email_log_status_check CHECK ((status = ANY (ARRAY['sent'::text, 'failed'::text, 'skipped_no_provider'::text])));
alter table public.email_log add constraint email_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.email_log add constraint email_log_dedup_key_key UNIQUE (dedup_key);
alter table public.favorites add constraint favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.favorites add constraint favorites_user_id_kind_item_slug_key UNIQUE (user_id, kind, item_slug);
alter table public.inquiries add constraint inquiries_listing_submission_id_fkey FOREIGN KEY (listing_submission_id) REFERENCES listing_submissions(id) ON DELETE SET NULL;
alter table public.inquiries add constraint inquiries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.listing_submissions add constraint listing_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.listing_submissions add constraint listing_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.payment_provider_events add constraint payment_provider_events_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_amount_cents_check CHECK ((amount_cents >= 0));
alter table public.payments add constraint payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.plans add constraint plans_billing_period_check CHECK ((billing_period = ANY (ARRAY['one_time'::text, 'monthly'::text, 'biannual'::text, 'yearly'::text])));
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.subscriptions add constraint subscriptions_billing_interval_check CHECK ((billing_interval = ANY (ARRAY['monthly'::text, 'biannual'::text, 'yearly'::text])));
alter table public.subscriptions add constraint subscriptions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'past_due'::text, 'cancelled'::text, 'expired'::text, 'trialing'::text])));
alter table public.subscriptions add constraint subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES plans(id);
alter table public.subscriptions add constraint subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.subscriptions add constraint subscriptions_user_id_key UNIQUE (user_id);

-- ============================================================
-- INDEXES (beyond those backing primary/unique constraints)
-- ============================================================
CREATE INDEX admin_audit_log_created_at_idx ON public.admin_audit_log USING btree (created_at DESC);
CREATE INDEX articles_status_published_idx ON public.articles USING btree (status, published_at DESC);
CREATE INDEX comments_article_slug_idx ON public.comments USING btree (article_slug);
CREATE INDEX email_log_created_at_idx ON public.email_log USING btree (created_at DESC);
CREATE INDEX inquiries_created_at_idx ON public.inquiries USING btree (created_at DESC);
CREATE INDEX inquiries_listing_submission_id_idx ON public.inquiries USING btree (listing_submission_id);
CREATE INDEX listing_submissions_created_at_idx ON public.listing_submissions USING btree (created_at DESC);
CREATE INDEX listing_submissions_featured_idx ON public.listing_submissions USING btree (is_featured_homepage) WHERE is_featured_homepage;
CREATE UNIQUE INDEX listing_submissions_slug_idx ON public.listing_submissions USING btree (slug);
CREATE INDEX listing_submissions_top_idx ON public.listing_submissions USING btree (is_top) WHERE is_top;
CREATE INDEX listing_submissions_user_id_idx ON public.listing_submissions USING btree (user_id);
CREATE INDEX payments_created_at_idx ON public.payments USING btree (created_at DESC);
CREATE INDEX payments_product_idx ON public.payments USING btree (product_type, product_id);
CREATE UNIQUE INDEX payments_provider_transaction_id_idx ON public.payments USING btree (provider, provider_transaction_id) WHERE (provider_transaction_id IS NOT NULL);
CREATE INDEX payments_status_idx ON public.payments USING btree (status);
CREATE INDEX payments_user_id_idx ON public.payments USING btree (user_id);
CREATE UNIQUE INDEX profiles_provider_slug_idx ON public.profiles USING btree (provider_slug) WHERE (provider_slug IS NOT NULL);
CREATE INDEX rate_limit_hits_bucket_created_idx ON public.rate_limit_hits USING btree (bucket_key, created_at DESC);
CREATE UNIQUE INDEX subscriptions_provider_subscription_id_idx ON public.subscriptions USING btree (provider, provider_subscription_id) WHERE (provider_subscription_id IS NOT NULL);

-- ============================================================
-- TRIGGERS
-- ============================================================
CREATE TRIGGER articles_set_updated_at BEFORE UPDATE ON public.articles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER comments_force_pending BEFORE INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION force_comment_pending();
CREATE TRIGGER payments_set_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER profiles_protect_role BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION prevent_role_self_escalation();
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER subscriptions_set_updated_at BEFORE UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- TRIGGERS ON auth.users (Supabase-managed schema — these tables already
-- exist in any Supabase project, only the triggers below need creating)
-- ============================================================
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER on_auth_user_created_subscription AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user_subscription();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table public.admin_audit_log enable row level security;
alter table public.articles enable row level security;
alter table public.comments enable row level security;
alter table public.email_log enable row level security;
alter table public.favorites enable row level security;
alter table public.inquiries enable row level security;
alter table public.listing_submissions enable row level security;
alter table public.payment_provider_events enable row level security;
alter table public.payments enable row level security;
alter table public.plans enable row level security;
alter table public.portal_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.promotion_addons enable row level security;
alter table public.rate_limit_hits enable row level security;
alter table public.subscriptions enable row level security;

create policy "admin_audit_log_select_admin" on public.admin_audit_log for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "articles_select_admin" on public.articles for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "articles_select_published" on public.articles for select to anon,authenticated
  using ((status = 'published'::article_status));
create policy "comments_insert_own" on public.comments for insert to authenticated
  with check ((auth.uid() = user_id));
create policy "comments_select_approved" on public.comments for select to anon,authenticated
  using ((status = 'approved'::comment_status));
create policy "comments_select_own" on public.comments for select to authenticated
  using ((auth.uid() = user_id));
create policy "email_log_select_admin" on public.email_log for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "favorites_delete_own" on public.favorites for delete to authenticated
  using ((auth.uid() = user_id));
create policy "favorites_insert_own" on public.favorites for insert to authenticated
  with check ((auth.uid() = user_id));
create policy "favorites_select_own" on public.favorites for select to authenticated
  using ((auth.uid() = user_id));
create policy "inquiries_insert_anyone" on public.inquiries for insert to anon,authenticated
  with check (true);
create policy "inquiries_select_admin" on public.inquiries for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "inquiries_select_own_listings" on public.inquiries for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM listing_submissions
  WHERE ((listing_submissions.id = inquiries.listing_submission_id) AND (listing_submissions.user_id = auth.uid())))));
create policy "inquiries_update_admin" on public.inquiries for update to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "inquiries_update_own_listings" on public.inquiries for update to authenticated
  using ((EXISTS ( SELECT 1
   FROM listing_submissions
  WHERE ((listing_submissions.id = inquiries.listing_submission_id) AND (listing_submissions.user_id = auth.uid())))))
  with check ((EXISTS ( SELECT 1
   FROM listing_submissions
  WHERE ((listing_submissions.id = inquiries.listing_submission_id) AND (listing_submissions.user_id = auth.uid())))));
create policy "listing_submissions_insert_own" on public.listing_submissions for insert to authenticated
  with check ((auth.uid() = user_id));
create policy "listing_submissions_select_admin" on public.listing_submissions for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "listing_submissions_select_own" on public.listing_submissions for select to authenticated
  using ((auth.uid() = user_id));
create policy "listing_submissions_select_published" on public.listing_submissions for select to anon,authenticated
  using ((status = 'published'::listing_submission_status));
create policy "listing_submissions_update_admin" on public.listing_submissions for update to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "listing_submissions_update_own" on public.listing_submissions for update to authenticated
  using ((auth.uid() = user_id))
  with check (((auth.uid() = user_id) AND (status <> 'published'::listing_submission_status) AND (status <> 'rejected'::listing_submission_status)));
create policy "payment_provider_events_select_admin" on public.payment_provider_events for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "payments_select_admin" on public.payments for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::user_role)))));
create policy "payments_select_own" on public.payments for select to authenticated
  using ((user_id = auth.uid()));
create policy "plans_select_all" on public.plans for select to anon,authenticated
  using ((is_active = true));
create policy "portal_settings_select_all" on public.portal_settings for select to anon,authenticated
  using (true);
create policy "profiles_select_own" on public.profiles for select to authenticated
  using ((auth.uid() = id));
create policy "profiles_update_own" on public.profiles for update to authenticated
  using ((auth.uid() = id))
  with check ((auth.uid() = id));
create policy "promotion_addons_select_all" on public.promotion_addons for select to anon,authenticated
  using (true);
create policy "subscriptions_select_own" on public.subscriptions for select to authenticated
  using ((auth.uid() = user_id));
